#!/usr/bin/env python3
"""
Generate production-ready secrets for AI Store Builder.
Usage: python scripts/generate_secrets.py [--env-file .env.production]
"""

import argparse
import os
import secrets
import string
import sys
from pathlib import Path


def generate_hex_secret(length: int = 64) -> str:
    """Generate a cryptographically secure hex string."""
    return secrets.token_hex(length)


def generate_password(length: int = 32) -> str:
    """Generate a strong password with mixed characters."""
    alphabet = string.ascii_letters + string.digits + "!@#$%^&*"
    while True:
        password = "".join(secrets.choice(alphabet) for _ in range(length))
        # Ensure at least one of each type
        if (
            any(c.islower() for c in password)
            and any(c.isupper() for c in password)
            and any(c.isdigit() for c in password)
            and any(c in "!@#$%^&*" for c in password)
        ):
            return password


def generate_secrets_dict(domain: str = "yourdomain.com") -> dict[str, str]:
    """Generate all required secrets for production."""
    db_password = generate_password(24)

    return {
        # App
        "APP_ENV": "production",
        "DEBUG": "false",
        # Database
        "DATABASE_URL": f"postgresql+asyncpg://aisb:{db_password}@localhost:5432/ai_store_builder",
        "POSTGRES_USER": "aisb",
        "POSTGRES_PASSWORD": db_password,
        "POSTGRES_DB": "ai_store_builder",
        # Redis
        "REDIS_URL": "redis://localhost:6379/0",
        # JWT — 128-byte hex (extremely secure)
        "JWT_SECRET_KEY": generate_hex_secret(64),
        "JWT_ALGORITHM": "HS256",
        "JWT_ACCESS_TOKEN_EXPIRE_MINUTES": "30",
        "JWT_REFRESH_TOKEN_EXPIRE_DAYS": "7",
        # Email
        "EMAIL_PROVIDER": "resend",
        "RESEND_API_KEY": "re_CHANGE_ME",
        "EMAIL_FROM_ADDRESS": f"noreply@{domain}",
        "FRONTEND_URL": f"https://{domain}",
        # CORS
        "CORS_ORIGINS": f'["https://{domain}","https://www.{domain}"]',
    }


def write_env_file(secrets_dict: dict[str, str], output_path: Path) -> None:
    """Write secrets to .env file."""
    lines = [
        "# ═══════════════════════════════════════════════════════════",
        "#  AI Store Builder — Production Environment",
        f"#  Generated by generate_secrets.py",
        f"#  ⚠️  KEEP THIS FILE SECURE — DO NOT COMMIT TO GIT",
        "# ═══════════════════════════════════════════════════════════",
        "",
    ]

    sections = {
        "App": ["APP_ENV", "DEBUG"],
        "Database": ["DATABASE_URL", "POSTGRES_USER", "POSTGRES_PASSWORD", "POSTGRES_DB"],
        "Redis": ["REDIS_URL"],
        "JWT Auth": [
            "JWT_SECRET_KEY",
            "JWT_ALGORITHM",
            "JWT_ACCESS_TOKEN_EXPIRE_MINUTES",
            "JWT_REFRESH_TOKEN_EXPIRE_DAYS",
        ],
        "Email": [
            "EMAIL_PROVIDER",
            "RESEND_API_KEY",
            "EMAIL_FROM_ADDRESS",
            "FRONTEND_URL",
        ],
        "CORS": ["CORS_ORIGINS"],
    }

    for section_name, keys in sections.items():
        lines.append(f"# ── {section_name} ──")
        for key in keys:
            if key in secrets_dict:
                lines.append(f"{key}={secrets_dict[key]}")
        lines.append("")

    # Add placeholder sections for optional services
    lines.extend(
        [
            "# ── AI (add your keys) ──",
            "ANTHROPIC_API_KEY=",
            "OPENAI_API_KEY=",
            "GOOGLE_API_KEY=",
            "",
            "# ── Payment Gateways ──",
            "MOYASAR_API_KEY=",
            "TAP_SECRET_KEY=",
            "",
            "# ── Cloudflare R2 Storage ──",
            "CLOUDFLARE_ACCOUNT_ID=",
            "R2_ACCESS_KEY_ID=",
            "R2_SECRET_ACCESS_KEY=",
            "R2_BUCKET_NAME=store-images",
            "R2_PUBLIC_URL=",
            "",
        ]
    )

    output_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate production secrets")
    parser.add_argument(
        "--env-file",
        default=".env.production",
        help="Output .env file path (default: .env.production)",
    )
    parser.add_argument(
        "--domain",
        default="yourdomain.com",
        help="Your production domain (default: yourdomain.com)",
    )
    parser.add_argument(
        "--print-only",
        action="store_true",
        help="Print secrets to stdout without writing file",
    )
    args = parser.parse_args()

    print("\n═══════════════════════════════════════")
    print("  AI Store Builder — Secret Generator")
    print("═══════════════════════════════════════\n")

    secrets_dict = generate_secrets_dict(domain=args.domain)

    if args.print_only:
        for key, value in secrets_dict.items():
            # Mask the actual secret values for display
            if any(word in key.lower() for word in ["secret", "password", "key"]):
                display = value[:8] + "..." + value[-4:] if len(value) > 16 else "****"
            else:
                display = value
            print(f"  {key}={display}")
    else:
        output_path = Path(args.env_file)
        if output_path.exists():
            response = input(f"  ⚠️  {output_path} already exists. Overwrite? [y/N] ")
            if response.lower() != "y":
                print("  Aborted.")
                sys.exit(0)

        write_env_file(secrets_dict, output_path)
        print(f"  ✅ Secrets written to: {output_path}")
        print(f"  📋 JWT Secret: {secrets_dict['JWT_SECRET_KEY'][:12]}...")
        print(f"  🔐 DB Password: {secrets_dict['POSTGRES_PASSWORD'][:8]}...")

    print("\n  ⚠️  IMPORTANT:")
    print("  1. Never commit .env.production to git")
    print("  2. Copy to VPS: scp .env.production root@YOUR_VPS:/opt/ai-store-builder/.env")
    print("  3. Set proper file permissions: chmod 600 /opt/ai-store-builder/.env")
    print("  4. Update RESEND_API_KEY with your actual key from https://resend.com")
    print("  5. Update AI keys if using AI features\n")


if __name__ == "__main__":
    main()
